# Hars 256 Color theme (adapted from spot)
# 8/2/2014
#
# Requires the 256 color patch for irssi
#
# Color List
# -----------
# Dark gray (bg)	%K
# Dark gray (fg)	%c
# Light blue (fg)	%b
# Bright green (fg)	%g

default_color = "-1";

replaces = { };

abstracts = {
  # Basics
  line_start = "%w%n";
  timestamp = "%c$*%n";
  hilight = "%g$*%n";
  error = "%r$*%n";
  channel = "$*";
  nick = "%b$*%n";
  nickhost = ":$*:";
  server = "%_$*%_";
  comment = "$*";
  reason = "{comment $*}";
  mode = "{comment $*}";

  # Channel 
  channick_hilight = "%g$*%n";
  chanhost_hilight = "{nickhost $*}";
  channick = "%r$*%n";
  chanhost = "{nickhost $*}";
  channelhilight = "%g$*%n";

  # Message
  msgnick = "$1%w$0 %w %|";
  ownmsgnick = "{msgnick $0 $1-}%w";
  ownnick = "%m$*%w";
  pubmsgnick = "{msgnick $0 $1-}%w";
  pubnick = "%b$*%w";
  pubmsgmenick = "{msgnick $0 $1-}%m";
  menick = "%w$*%c";
  pubmsghinick = "{msgnick $1 $0$2-%n}%m";
  msgchannel = ":$*";
  privmsg = ">%n$0(%b$1-)> ";
  ownprivmsg = "~%m$0(%c$1-)~ %w";
  ownprivmsgnick = "{msgnick   $*}%w%|";
  ownprivnick = "%m$*%w%|";
  privmsgnick = "{msgnick   %w$*%n}%|";

  # Actions
  action_core = "%w$*%N";
  action = "{action_core $*} ";
  ownaction = "{action %M$*}%w";
  ownaction_target = "{action_core $0}:$1 ";
  pvtaction = "%B(*)%m $* ";
  pvtaction_query = "{action $*}";
  pubaction = "{action %r$*}";
  ban = "%r$*%n";
  whois = "  $[8]0 : $1-";
  ownnotice = "[%w$0(%c$1-)]%w ";
  notice = "-%m$*%n- ";
  pubnotice_channel = ":$*";
  pvtnotice_host = "(%c$*)";
  servernotice = "%m!$*%n ";
  ownctcp = "[%B$0(%c$1-)] ";
  ctcp = "%m$*%n";

  # Wallop
  wallop = "%W$*%n: ";
  wallop_nick = "%n$*";
  wallop_action = "%W * $*%n ";
  netsplit = "%r$*%n";
  netjoin = "%m$*%n";

  # Names
  names_prefix = "";
  names_nick = "^%m$0%z00afff$1- ";
  names_nick_op = "{names_nick $*}";
  names_nick_halfop = "{names_nick $*}";
  names_nick_voice = "{names_nick $*}";
  names_users = "-%w$*%n-";
  names_channel = "%w$*%n";

  # DCC
  dcc = "%c$*%n";
  dccfile = "%_$*%_";
  dccownmsg = "[%n$0(%c$1-)] ";
  dccownnick = "%w$*%n";
  dccownaction = "{action %W$*}%w";
  dccownaction_target = "{action_core $0}:%c$1%n ";
  dccmsg = "[%w$1-(%c$0)] ";
  dccquerynick = "%c$*%n";
  dccaction = "%W (*dcc*) $*%n %|";

  # Status bar
  sb_background = "%6";
  sb_topic_bg = "%6%w";
  sb_info_bg = "%4%m";
  sbstart = "";
  sbend = "";
  prompt = "$*%w: ";
  sb = "%w $*";
  sbmode = "%m(%W+%m$*%m)%m";
  sbaway = "%w %R %r^_^ %b$0";
  sbservertag = ":$0";
  sb_act_none = "%n$*";
  sb_act_sep = "%n$*";
  sb_act_text = "%r$*";
  sb_act_msg = "%m$*";
  sb_act_hilight = "%r$*";
  sb_act_hilight_color = "$0$1-%n";
};
formats = {
  idea = {
    idea_own_msg = "{ownmsgnick $2 {ownnick $[-15]0}}%G$1";
    idea_own_msg_channel = "{ownmsgnick $3 {ownnick $[-15]0}{msgchannel $1}}%G$2";
    idea_own_msg_private = "{ownprivmsg msg $0}%G$1";
    idea_own_msg_private_query = "privmsgnick $[-15]0}%g$2";
    idea_pubmsg_me = "{pubmsgmenick $2 {menick $[-15]0}}%g$1";
    idea_pubmsg_me_channel = "{pubmsgmenick $3 {menick $[-15]0}{msgchannel $1}}%g$2";
    idea_pubmsg_hilight = "{pubmsghinick $0 $3 $[-15]1}%G$2";
    idea_pubmsg_hilight_channel = "{pubmsghinick $0 $4 $[-15]1{msgchannel $2}}%G$3";
    idea_pubmsg = "{pubmsgnick $2 {pubnick $[-15]0}}%g$1";
    idea_pubmsg_channel = "{pubmsgnick $3 {pubnick $[-15]0}{msgchannel $1}}%g$2";
    idea_msg_private = "{privmsg $0 $1}%g$2";
    idea_msg_private_query = "{privmsgnick $[-15]0}%g$2";
  };
  "fe-common/core" = {
    join = "{channick_hilight $[-15]0} %w-->%n {chanhost_hilight $1} joins {channel $2}";
    part = "{channick $[-15]0} %n<--%n {chanhost $1} leaves {channel $2} {reason $3}";
    quit = "{channick $[-15]0} %c<--%n {chanhost $1} quits {reason $[.50]2}";
    kick = "{channick $[-15]0} %r:(%n was kicked from {channel $1} by {nick $2} {reason $3}";
    nick_changed = "{channick $[-15]0} %w<>%m changes nick to {channick_hilight $1}";
    own_msg = "{ownmsgnick {ownnick $[-10]0$2}}$1";
    own_msg_channel = "{ownmsgnick {ownnick $[-10]0$3}{msgchannel $1}}$2";
    pubmsg_me = "{pubmsgmenick {menick $[-14]0}$2}$1";
    pubmsg_me_channel = "{pubmsgmenick {menick $[-14]0$3}{msgchannel $1}}$2";
    pubmsg_hilight = "{pubmsghinick $0 $0 $[-14]1$3%n}$2";
    pubmsg_hilight_channel = "{pubmsghinick $0 $0 $[-14]1$4{msgchannel $2}}$3";
    pubmsg = "{pubmsgnick {pubnick $nickcolor$[-14]0$2}}$1";
    pubmsg_channel = "{pubmsgnick {pubnick $nickcolor$[-14]0$3}{msgchannel $1}}$2";
    own_msg_private = "{ownprivmsg msg $0}$1";
    own_msg_private_query = "{ownprivmsgnick {ownprivnick $[-10]2}}$1";
    msg_private_query = "{privmsgnick $[-6]0}$2";
    msg_private = "{privmsg $0 $1}$2";
  };
  "fe-common/irc" = {
    chanmode_change = "{hilight %n~~~ %m{nick $2}} %n sets%m{mode $1} %w on {channelhilight $0 %n~~~}";
    own_action = "{ownaction $[-10]0}$1";
    action_private = "{pvtaction $0}$2";
    action_private_query = "{pvtaction_query $[-9]0}$2";
    action_public_channel = "{pubaction $[-10]0{msgchannel $1}}$2";
    action_public = "{pubaction $[-10]0}$1";
    netsplit = "{netsplit    Netsplit} %r<···%n {server $0} %W<%n-%W>%n {server $1} quits: $2";
    netsplit_more = "{netsplit    Netsplit} %w<··%n {server $0} %W<%n-%W>%n {server $1} quits: $2 (%K+$3 more%n)";
    netsplit_join = "{netjoin    Netsplit} %c··>%n $0";
    netsplit_join_more = "{netjoin    Netsplit} %w>%n $0 (%K+$1 more%n)";
    server_chanmode_change = "{netsplit   {nick $2}}/{channelhilight $0} sets {mode $1} ";
  };
  "fe-common/irc/dcc" = {
    own_dcc_action_query = "{dccownaction $[-9]0}$2";
    dcc_msg_query = "{privmsgnick $[-9]0}$1";
    own_dcc_query = "{ownmsgnick {ownnick $[-9]0}} $2";
  };
};
